language: java
jdk:
- oraclejdk8
script: ant build
addons:
  sonarcloud:
    organization: "jeevan1133-github" # the key of the org you chose at step #3
    token:
      secure: "b180b0e40d6b3af93b27d461b57e7a9bcec7a517"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
